apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-bot
  template:
    metadata:
      labels:
        app: hello-bot
    spec:
      containers:
        - name: bot
          image: 1t1scool/echo-bot:latest
          env:
            - name: HELLO_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tg-hello-bot-token
                  key: HELLO_BOT_TOKEN
